# Generated by Django 5.0 on 2023-12-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_inventory_alter_menu_price_alter_menu_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Inventory',
            new_name='inventory',
        ),
    ]
